### ISSUE TITLE
Audio-advance settings don't save

### ISSUE THREAD

**Issue by raafirivero** [gobbledegook/creevey#7]
I generally turn auto-advance off. However, whenever I relaunch the app, auto-advance is turned back on. The number of seconds does save. The workaround I've found is to set auto-advance to 0 seconds, but the checkbox remains checked once I've relaunched the app.

**Comment by kode54** [comment]
I have experienced a different issue with auto advance. Not so much the auto advance not saving, since I leave it turned on. Rather, the number of seconds doesn't cause the Apply button to enable, and if I toggle any of the other settings to make the Apply button enable, it doesn't seem to save the time setting. I change it from the 5.25 default to double that, 10.5, and it still acts like it's timing by 5.25 seconds.

**Comment by gobbledegook** [comment]
this should be fixed in v1.5.3
